### ISSUE TITLE
Segfault when parsing block models

### ISSUE THREAD

**Issue by z-targz** [LaG1924/AltCraft#55] opened 2021-03-27 00:52 UTC
The application segfaults when parsing blockmodels when comparing Uv with the overloaded operator according to my debugger.
System: Ubuntu 20.04

**Comment by LaG1924** [comment] 2021-03-27 01:00
Thanks. I assume that the segfault was due to null pointer.
Unfortunately, without a full call stack (at least a couple of frames up) it will be difficult to determine where the call was made over a null pointer ... And a full dump would be absolutely good.
Most likely, refactoring the resource loading will resolve this error, but you will have to wait some more time before that.
I can also advise you to check the availability and correctness of the assets used.

**Comment by uis246** [comment] 2021-03-27 06:48
https://github.com/uis246/AltCraft
Check this. Will it reproduce?

**Comment by LaG1924** [comment] 2021-06-28 16:06
Fixed in 33c756b38e94cef68b3f842c1c2f8bad9d4447a2

**Closed by LaG1924** 2021-06-28 16:06 UTC
